apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-api
  namespace: payments
  labels:
    app: ledger-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: ledger-api

  template:
    metadata:
      labels:
        app: ledger-api

    spec:
      containers:
        - name: ledger-api
          image: ledger-api:starter
          imagePullPolicy: IfNotPresent

          env:
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ledger-api-secret
                  key: stripe-api-key

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ledger-api-secret
                  key: db-password

          ports:
            - containerPort: 8080