name: Secure DevSecOps Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: Gitleaks Secrets Scan
        uses: gitleaks/gitleaks-action@v2

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL